services:
  mcp-inspector:
    image: ghcr.io/modelcontextprotocol/inspector:latest
    ports:
      - '6274:6274'
      - '6277:6277'
    environment:
      - DANGEROUSLY_OMIT_AUTH=true
      - HOST=0.0.0.0
    restart: unless-stopped
    container_name: mcp-inspector-sveltejs-mcp

  adminer:
    image: adminer:4.6.2
    ports:
      - '8081:8080'
    volumes:
      - ./test.db:/tmp/test.db
      - ./bypass.php:/var/www/html/bypass.php
    environment:
      - ADMINER_DEFAULT_SERVER=sqlite:/tmp/test.db
      - ADMINER_DESIGN=hydra
    restart: unless-stopped
    container_name: adminer-sveltejs-mcp
    command: ["php", "-S", "[::]:8080", "-t", "/var/www/html", "/var/www/html/bypass.php"]
