onlyBuiltDependencies:
  - esbuild
packages:
  - './packages/*'
  - './apps/*'

useNodeVersion: 22.19.0

catalogs:
  tmcp:
    tmcp: '^1.16.0'
    '@tmcp/transport-http': '^0.8.0'
    '@tmcp/transport-stdio': '^0.4.0'
    '@tmcp/adapter-valibot': '^0.1.4'

  ai:
    '@anthropic-ai/sdk': ^0.68.0
    '@mcp-ui/server': ^5.12.0
    '@modelcontextprotocol/inspector': ^0.17.0

  lint:
    eslint: ^9.36.0
    '@types/eslint-scope': ^8.3.2
    '@eslint/compat': ^1.3.2
    '@eslint/js': ^9.36.0
    '@typescript-eslint/parser': ^8.44.0
    '@typescript-eslint/types': ^8.44.0
    eslint-config-prettier: ^10.0.1
    eslint-plugin-import: ^2.32.0
    eslint-plugin-svelte: ^3.12.5
    svelte-eslint-parser: ^1.4.0
    typescript-eslint: ^8.44.0
    globals: ^16.0.0
    jsonc-eslint-parser: ^2.4.1
    yaml-eslint-parser: ^1.3.0
    prettier: ^3.4.2
    prettier-plugin-svelte: ^3.3.3

  orm:
    '@libsql/client': ^0.15.0
    drizzle-kit: ^0.31.0
    drizzle-orm: ^0.44.0

  svelte:
    '@sveltejs/adapter-vercel': ^6.0.0
    '@sveltejs/kit': ^2.42.2
    '@sveltejs/vite-plugin-svelte': ^6.0.0
    svelte: ^5.39.2
    svelte-check: ^4.0.0

  tooling:
    '@changesets/cli': ^2.29.7
    '@svitejs/changesets-changelog-github-compact': ^1.2.0
    '@types/estree': ^1.0.8
    '@types/node': ^24.3.1
    '@vercel/analytics': ^1.5.0
    dotenv: ^17.2.3
    node-resolve-ts: ^1.0.2
    publint: ^0.3.13
    ts-blank-space: ^0.6.2
    tsdown: ^0.15.0
    typescript: ^5.0.0
    valibot: ^1.1.0
    vite: ^7.0.4
    vite-plugin-devtools-json: ^1.0.0
    vitest: ^4.0.0
    zimmerframe: ^1.1.4

  # TODO: Do we need these specific versions?
  specific_versions:
    '@types/node': ^22.15.17
    typescript: ^5.8.3
