name: "\U0001F41E Bug report"
description: Report an issue with Svelte
title: '[Bug] '
labels: ['triage: bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide a link to a repo or REPL that can reproduce the problem you ran into. If a report is vague (e.g. just a generic error message) and has no reproduction, it will receive a "need reproduction" label. If no reproduction is provided within a reasonable time-frame, the issue will be closed.
      placeholder: Reproduction
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: 'Please provide some logs or screenshot of the agentic workflow failing.'
      render: shell
  - type: input
    id: mcp-client
    attributes:
      label: MCP Client
      description: Which MCP client are you using?
      render: shell
      placeholder: claude-code, codex, opencode
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: Select the severity of this issue
      options:
        - annoyance
        - minor functionality loss
        - major functionality loss
        - blocking all usage of the mcp
    validations:
      required: true
